#!/bin/bash
cd /etc/sysconfig/network-scripts/

# Check that it's bonded first of all
if [ ! -f ifcfg-bond0 ]; then
  echo "No bonded interface, exiting"
  exit 0
fi

IFLIST=`grep MASTER ifcfg-eth*|cut -f1 -d:|cut -f2 -d-`
EXTRAIP=`ls  ifcfg-bond0:*|wc -l`
IF1=`echo $IFLIST|cut -f1 -d' '`
IF2=`echo $IFLIST|cut -f2 -d' '`

echo "IF1:$IF1 IF2:$IF2"

if [ $EXTRAIP -eq 0 ]; then
  mv -f ifcfg-bond0 ifcfg-$IF1
  sed -i "s+bond0+$IF1+g" ifcfg-$IF1
  sed -i '/BONDING/d' ifcfg-$IF1
  HW=`grep HWA ifcfg-$IF2`
  echo "DEVICE=$IF2" > ifcfg-$IF2
  echo $HW >> ifcfg-$IF2
  echo "ONBOOT=no" >> ifcfg-$IF2
fi

if [ $EXTRAIP -eq 1 ]; then
  mv -f ifcfg-bond0 ifcfg-$IF1
  mv -f ifcfg-bond0:? ifcfg-$IF2
  sed -i "s+bond0+$IF1+g" ifcfg-$IF1
  sed -i '/BONDING/d' ifcfg-$IF1
  sed -i "s+bond0:[0-9]+$IF2+g" ifcfg-$IF2
  sed -i '/BONDING/d' ifcfg-$IF2
fi
